version: 2
jobs:
   build_can:
     docker:
       - image: koppor/texlive
     steps:
       - checkout
       - run: 
           command: make
           working_directory: CanDetector
       - store_artifacts:
           path: CanDetector/master.pdf
   build_sem:
     docker:
       - image: koppor/texlive
     steps:
       - checkout
       - run: 
           command: make
           working_directory: SemiconductorDetector
       - store_artifacts:
           path: SemiconductorDetector/report_semiconductor_detector.pdf
workflows:
  version: 2
  build_all:
    jobs:
      - build_can
      - build_sem
