version: 2
jobs:
   build:
     docker:
       - image: koppor/texlive
     steps:
       - checkout
       - run: 
           command: pdflatex master.tex
           working_directory: CanDetector
       - store_artifacts:
           path: CanDetector/master.pdf
